/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LngRouteImport } from './routes/$lng'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LngIndexRouteImport } from './routes/$lng.index'
import { Route as LngCoverLetterRouteImport } from './routes/$lng.cover-letter'

const LngRoute = LngRouteImport.update({
  id: '/$lng',
  path: '/$lng',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LngIndexRoute = LngIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LngRoute,
} as any)
const LngCoverLetterRoute = LngCoverLetterRouteImport.update({
  id: '/cover-letter',
  path: '/cover-letter',
  getParentRoute: () => LngRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lng': typeof LngRouteWithChildren
  '/$lng/cover-letter': typeof LngCoverLetterRoute
  '/$lng/': typeof LngIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lng/cover-letter': typeof LngCoverLetterRoute
  '/$lng': typeof LngIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lng': typeof LngRouteWithChildren
  '/$lng/cover-letter': typeof LngCoverLetterRoute
  '/$lng/': typeof LngIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$lng' | '/$lng/cover-letter' | '/$lng/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$lng/cover-letter' | '/$lng'
  id: '__root__' | '/' | '/$lng' | '/$lng/cover-letter' | '/$lng/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LngRoute: typeof LngRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lng': {
      id: '/$lng'
      path: '/$lng'
      fullPath: '/$lng'
      preLoaderRoute: typeof LngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lng/': {
      id: '/$lng/'
      path: '/'
      fullPath: '/$lng/'
      preLoaderRoute: typeof LngIndexRouteImport
      parentRoute: typeof LngRoute
    }
    '/$lng/cover-letter': {
      id: '/$lng/cover-letter'
      path: '/cover-letter'
      fullPath: '/$lng/cover-letter'
      preLoaderRoute: typeof LngCoverLetterRouteImport
      parentRoute: typeof LngRoute
    }
  }
}

interface LngRouteChildren {
  LngCoverLetterRoute: typeof LngCoverLetterRoute
  LngIndexRoute: typeof LngIndexRoute
}

const LngRouteChildren: LngRouteChildren = {
  LngCoverLetterRoute: LngCoverLetterRoute,
  LngIndexRoute: LngIndexRoute,
}

const LngRouteWithChildren = LngRoute._addFileChildren(LngRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LngRoute: LngRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
