/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LngChar125RouteImport } from './routes/{-$lng}'
import { Route as ResumeCompanyRouteImport } from './routes/resume.$company'
import { Route as Char123LngChar125IndexRouteImport } from './routes/{-$lng}.index'
import { Route as Char123LngChar125CoverLetterRouteImport } from './routes/{-$lng}.cover-letter'

const Char123LngChar125Route = Char123LngChar125RouteImport.update({
  id: '/{-$lng}',
  path: '/{-$lng}',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeCompanyRoute = ResumeCompanyRouteImport.update({
  id: '/resume/$company',
  path: '/resume/$company',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LngChar125IndexRoute = Char123LngChar125IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Char123LngChar125Route,
} as any)
const Char123LngChar125CoverLetterRoute =
  Char123LngChar125CoverLetterRouteImport.update({
    id: '/cover-letter',
    path: '/cover-letter',
    getParentRoute: () => Char123LngChar125Route,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$lng}': typeof Char123LngChar125RouteWithChildren
  '/resume/$company': typeof ResumeCompanyRoute
  '/{-$lng}/cover-letter': typeof Char123LngChar125CoverLetterRoute
  '/{-$lng}/': typeof Char123LngChar125IndexRoute
}
export interface FileRoutesByTo {
  '/resume/$company': typeof ResumeCompanyRoute
  '/{-$lng}/cover-letter': typeof Char123LngChar125CoverLetterRoute
  '/{-$lng}': typeof Char123LngChar125IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$lng}': typeof Char123LngChar125RouteWithChildren
  '/resume/$company': typeof ResumeCompanyRoute
  '/{-$lng}/cover-letter': typeof Char123LngChar125CoverLetterRoute
  '/{-$lng}/': typeof Char123LngChar125IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$lng}'
    | '/resume/$company'
    | '/{-$lng}/cover-letter'
    | '/{-$lng}/'
  fileRoutesByTo: FileRoutesByTo
  to: '/resume/$company' | '/{-$lng}/cover-letter' | '/{-$lng}'
  id:
    | '__root__'
    | '/{-$lng}'
    | '/resume/$company'
    | '/{-$lng}/cover-letter'
    | '/{-$lng}/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LngChar125Route: typeof Char123LngChar125RouteWithChildren
  ResumeCompanyRoute: typeof ResumeCompanyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$lng}': {
      id: '/{-$lng}'
      path: '/{-$lng}'
      fullPath: '/{-$lng}'
      preLoaderRoute: typeof Char123LngChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume/$company': {
      id: '/resume/$company'
      path: '/resume/$company'
      fullPath: '/resume/$company'
      preLoaderRoute: typeof ResumeCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lng}/': {
      id: '/{-$lng}/'
      path: '/'
      fullPath: '/{-$lng}/'
      preLoaderRoute: typeof Char123LngChar125IndexRouteImport
      parentRoute: typeof Char123LngChar125Route
    }
    '/{-$lng}/cover-letter': {
      id: '/{-$lng}/cover-letter'
      path: '/cover-letter'
      fullPath: '/{-$lng}/cover-letter'
      preLoaderRoute: typeof Char123LngChar125CoverLetterRouteImport
      parentRoute: typeof Char123LngChar125Route
    }
  }
}

interface Char123LngChar125RouteChildren {
  Char123LngChar125CoverLetterRoute: typeof Char123LngChar125CoverLetterRoute
  Char123LngChar125IndexRoute: typeof Char123LngChar125IndexRoute
}

const Char123LngChar125RouteChildren: Char123LngChar125RouteChildren = {
  Char123LngChar125CoverLetterRoute: Char123LngChar125CoverLetterRoute,
  Char123LngChar125IndexRoute: Char123LngChar125IndexRoute,
}

const Char123LngChar125RouteWithChildren =
  Char123LngChar125Route._addFileChildren(Char123LngChar125RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  Char123LngChar125Route: Char123LngChar125RouteWithChildren,
  ResumeCompanyRoute: ResumeCompanyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
